# Connexion au source de donnee

## CSV (Comman Separate Values) et Excel avec pandas

In [6]:
import pandas as pd

In [3]:
# Lecture excel
file_excel = pd.read_excel("data/ressources_humaines.xlsx")
file_excel

,matricule,prenom,nom,sexe,age,id_magasin,ville,poste,date_embauche,type_contrat,salaire_brut_mensuel,satisfaction_1_10
0,EMP0001,Arthur,Nguyen,F,59,10,Nice,Responsable rayon,2018-11-11,CDI,3289.0,9
1,EMP0002,Fatou,David,F,40,8,Strasbourg,Caissier,2021-03-17,CDD,1852.0,5
2,EMP0003,Arthur,Dupont,F,50,10,Nice,Vendeur,2021-01-30,Alternance,2020.0,4
3,EMP0004,Inès,Diallo,M,48,4,Toulouse,Responsable rayon,2014-10-20,CDI,3065.0,4
4,EMP0005,Karim,Leroy,M,48,6,Bordeaux,Vendeur,2017-02-16,CDI,2207.0,7
...,...,...,...,...,...,...,...,...,...,...,...,...
115,EMP0116,Léa,Girard,F,48,4,Toulouse,Directeur de magasin,2016-02-19,CDI,4015.0,4
116,EMP0117,Awa,Simon,M,55,8,Strasbourg,Responsable rayon,2012-04-14,CDI,3044.0,7
117,EMP0118,Zoé,Durand,F,40,10,Nice,Conseiller,2023-10-31,Alternance,2264.0,7
118,EMP0119,Moussa,Roux,F,60,3,Marseille,Conseiller,2019-03-31,CDD,2350.0,9
119,EMP0120,Zoé,Benali,F,41,8,Strasbourg,Directeur de magasin,2017-08-03,CDD,3526.0,5

In [4]:
# Ajouter une colonne contenant la satisfaction en %
file_excel["satisfaction_percent"] = (file_excel["satisfaction_1_10"] * 100)/10
file_excel

,matricule,prenom,nom,sexe,age,id_magasin,ville,poste,date_embauche,type_contrat,salaire_brut_mensuel,satisfaction_1_10,satisfaction_percent
0,EMP0001,Arthur,Nguyen,F,59,10,Nice,Responsable rayon,2018-11-11,CDI,3289.0,9,90.0
1,EMP0002,Fatou,David,F,40,8,Strasbourg,Caissier,2021-03-17,CDD,1852.0,5,50.0
2,EMP0003,Arthur,Dupont,F,50,10,Nice,Vendeur,2021-01-30,Alternance,2020.0,4,40.0
3,EMP0004,Inès,Diallo,M,48,4,Toulouse,Responsable rayon,2014-10-20,CDI,3065.0,4,40.0
4,EMP0005,Karim,Leroy,M,48,6,Bordeaux,Vendeur,2017-02-16,CDI,2207.0,7,70.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,EMP0116,Léa,Girard,F,48,4,Toulouse,Directeur de magasin,2016-02-19,CDI,4015.0,4,40.0
116,EMP0117,Awa,Simon,M,55,8,Strasbourg,Responsable rayon,2012-04-14,CDI,3044.0,7,70.0
117,EMP0118,Zoé,Durand,F,40,10,Nice,Conseiller,2023-10-31,Alternance,2264.0,7,70.0
118,EMP0119,Moussa,Roux,F,60,3,Marseille,Conseiller,2019-03-31,CDD,2350.0,9,90.0
119,EMP0120,Zoé,Benali,F,41,8,Strasbourg,Directeur de magasin,2017-08-03,CDD,3526.0,5,50.0

In [9]:
# Lecture du fichier csv
file_csv = pd.read_csv("data/avis_clients.csv", sep=";")
file_csv

,id_avis,id_client,id_produit,date_avis,note,recommande,commentaire
0,1,89,9,10/05/2025,2.0,non,Livraison lente
1,2,27,13,04/07/2025,1.0,non,Produit défectueux
2,3,213,26,11/07/2025,4.0,oui,Satisfait
3,4,183,3,14/03/2025,5.0,Non,"Parfait, je recommande"
4,5,55,5,12/07/2024,3.0,OUI,Sans plus
...,...,...,...,...,...,...,...
807,616,263,24,25/07/2024,5.0,OUI,"Parfait, je recommande"
808,28,268,24,25/06/2024,5.0,oui,Excellent !
809,786,33,4,19/09/2025,4.0,oui,Satisfait
810,239,148,24,19/10/2025,5.0,oui,Excellent !
811,476,271,7,04/08/2025,4.0,OUI,Satisfait

## Fichier plat

In [18]:
file_plat = open("data/livraisons.txt", "r")
file_contenu = file_plat.readlines()
file_plat.close()

In [19]:
for line in file_contenu:
    print(line)

       1       1Chronopost       2024070420240709    18.28    6.17LIVRE

       2       7Colissimo        20240417            15.49   17.40EN_TRANSIT

       3       9DHL              2024030520240307     9.08   18.89LIVRE

       4      10Mondial Relay    2025100520251007    15.87    2.62LIVRE

       5      11UPS              2025092920251001     3.18    8.17RETARD

       6      12DHL              2024110320241106    22.32   14.25LIVRE

       7      14Colissimo        2025041820250420    11.56   18.70RETARD

       8      18DHL              2024092320240924    15.26   13.12LIVRE

       9      19UPS              2024060520240608    11.62    1.54LIVRE

      10      20UPS              2024052620240529     0.79   18.57LIVRE

      11      22Colissimo        2025061220250615     1.29   18.24LIVRE

      12      23Chronopost       2025021220250215    15.08    9.66LIVRE

      13      24DHL              2025081420250817    20.02   17.83LIVRE

      14      25Chronopost       20250624            13.96    2.27EN_TRANSIT

      15      28Colissimo        2025072520250728    13.28   13.63LIVRE

      16      30DHL              2025120520251213    15.77   13.15RETARD

      17      31Mondial Relay    2024020620240208    13.50    3.19LIVRE

      18      33UPS              2024110320241104    23.74   14.22RETARD

      19      35Mondial Relay    20250807             2.98   13.31EN_TRANSIT

      20      36UPS              2024052020240522     5.43    8.36LIVRE

      21      37Colissimo        2025011920250121    23.99    4.42LIVRE

      22      41Mondial Relay    2024032820240331    19.05   11.62LIVRE

      23      42DHL              2025110420251105    15.27    4.07LIVRE

      24      44UPS              2025050720250512     6.73    0.70LIVRE

      25      47UPS              2025031820250320    11.35    1.36LIVRE

      26      48Colissimo        2025121020251213    10.74    7.05LIVRE

      27      51Mondial Relay    20240210            19.93   16.34EN_TRANSIT

      28      52Colissimo        2025122020260104    12.69   18.23LIVRE

      29      53Colissimo        2025070620250708    18.05    2.68LIVRE

      30      56Chronopost       2024020220240204     6.16    9.35LIVRE

      31      57Chronopost       2025010620250108     2.67    9.85LIVRE

      32      61Chronopost       20240112            21.02    2.14EN_TRANSIT

      33      62Colissimo        2024060520240608    21.33    2.86LIVRE

      34      66DHL              2025121820251219     8.56    0.47LIVRE

      35      67Colissimo        2025082120250905    12.78   14.81LIVRE

      36      68Mondial Relay    2024073120240803    21.10   11.30LIVRE

      37      70Mondial Relay    2025022120250223    12.85    2.69LIVRE

      38      74Chronopost       2024101120241012    20.00   15.36LIVRE

      39      75Colissimo        2024030420240307     0.88   11.55LIVRE

      40      76DHL              2025100920251011    15.54    4.50LIVRE

      41      77DHL              2024012720240129     2.84   19.73LIVRE

      42      82DHL              20251225            10.45    7.71EN_TRANSIT

      43      83Mondial Relay    2025101920251022    15.22    7.51LIVRE

      44      84DHL              2025012320250125    15.87    1.11LIVRE

      45      86Chronopost       2025040320250404    22.44    5.71RETARD

      46      87Colissimo        2025030720250309     4.77    1.57LIVRE

      47      88DHL              2024061720240619     2.74   10.28LIVRE

      48      90Mondial Relay    20251223            22.09    0.24EN_TRANSIT

      49      92Mondial Relay    2024022520240227    20.07   16.91LIVRE

      50      94Mondial Relay    2025021220250215     7.49    5.48LIVRE

      51      95Chronopost       2024092620240929    10.52    6.50LIVRE

      52      97Mondial Relay    2025081220250814    20.30   17.02LIVRE

      53      99Chronopost       2024112520241127     4.17   19.44LIVRE

      54     102UPS              2024020920240211     4.95    1.40LIVRE

      55     105Colissimo        20250615             7.65    0.83EN_TRANSIT

      56     107Colissimo        20241007            22.85    0.63EN_TRANSIT

      57     109Mondial Relay    2024101920241021    20.34   18.31LIVRE

      58     110Chronopost       20250430            16.80    8.13EN_TRANSIT

      59     111Colissimo        2024122620241227    21.86   11.30LIVRE

      60     112Mondial Relay    20240414            20.15   12.25EN_TRANSIT

      61     113Mondial Relay    2025101920251024     3.75    6.05LIVRE

      62     115Mondial Relay    20250221            16.79    4.21EN_TRANSIT

      63     118Colissimo        2024120520241213     7.17    3.94LIVRE

      64     120Mondial Relay    2024032320240325    15.91    6.21LIVRE

      65     123Chronopost       2024051420240522     4.08   12.66LIVRE

      66     125DHL              2024062520240630     7.93    0.77LIVRE

      67     126DHL              2025120920251211    19.85   16.05LIVRE

      68     129Mondial Relay    2024061620240618    11.58    4.23LIVRE

      69     133DHL              2024121620241218    19.12    7.76LIVRE

      70     135Chronopost       2025051120250513    11.55   13.16LIVRE

      71     137UPS              2024060420240607    18.20    0.54LIVRE

      72     138DHL              2024112520241130     6.61   12.49LIVRE

      73     139Chronopost       2025040620250407    15.29   14.09LIVRE

      74     142DHL              2024042920240502     2.41   16.23LIVRE

      75     143UPS              2025062120250629     0.62    3.34LIVRE

      76     145Mondial Relay    2025040920250411     1.33    9.73LIVRE

      77     147Colissimo        20250603             2.21   19.83EN_TRANSIT

      78     151Colissimo        2024053120240603     4.31    4.49LIVRE

      79     152Colissimo        2024052920240531     7.17    5.78LIVRE

      80     156Mondial Relay    2024050520240507     9.59   12.65LIVRE

      81     157Mondial Relay    20240212             1.92    0.24EN_TRANSIT

      82     159Colissimo        2025021820250220    23.05    9.07LIVRE

      83     161UPS              2025020220250203    23.75   15.23LIVRE

      84     165DHL              20240119            14.44    6.17EN_TRANSIT

      85     169Colissimo        2024121920241224    11.21    2.05LIVRE

      86     171UPS              2025051320250515    20.84   19.75LIVRE

      87     174Colissimo        2025040320250406     6.85    5.85LIVRE

      88     177UPS              2024051920240521     7.13    4.62LIVRE

      89     178DHL              2025061220250615     9.48    3.22LIVRE

      90     179Chronopost       2024021120240213    18.23    7.17LIVRE

      91     180DHL              2025061420250619    15.51   15.86LIVRE

      92     181UPS              20251011            24.50    4.27EN_TRANSIT

      93     182Mondial Relay    20240917            12.05   16.55EN_TRANSIT

      94     183Mondial Relay    2025091120250912    21.75   15.19LIVRE

      95     184UPS              20240603            18.00    3.03EN_TRANSIT

      96     186Mondial Relay    20240228            20.60   16.83EN_TRANSIT

      97     187Chronopost       20240626            20.92    3.05EN_TRANSIT

      98     188UPS              2024093020241003    16.66    5.19LIVRE

      99     192DHL              2025090420250919    14.50   15.74LIVRE

     100     193Colissimo        2025062220250630    10.87    7.27LIVRE

     101     194Chronopost       20240916            20.65    9.20EN_TRANSIT

     102     201UPS              2025072720250728     3.58    0.49LIVRE

     103     204DHL              2025050920250517     9.95    7.97LIVRE

     104     205DHL              2025070520250706     9.14    0.10LIVRE

     105     206Chronopost       2025072220250725    11.99   16.71LIVRE

     106     209UPS              2025051720250520    23.85   11.61LIVRE

     107     210Chronopost       20250505            15.19   16.96EN_TRANSIT

     108     212Chronopost       2025071520250717     9.86    1.07LIVRE

     109     214Colissimo        2025012520250128    16.75   14.92LIVRE

     110     216UPS              2025100620251011     1.95   11.65LIVRE

     111     220Mondial Relay    2025122920260101    15.74    1.63LIVRE

     112     221Mondial Relay    2025110820251113    12.90   13.04RETARD

     113     222DHL              20240226            16.72    7.47EN_TRANSIT

     114     224Mondial Relay    20250423            21.35    9.51EN_TRANSIT

     115     226Colissimo        2024111220241115     6.74    5.22LIVRE

     116     230UPS              20241023            23.73    4.88EN_TRANSIT

     117     231DHL              2024012320240128    18.17    1.40LIVRE

     118     232Mondial Relay    2025011620250117    13.76   17.49LIVRE

     119     233Mondial Relay    2025020520250207    18.24    7.91LIVRE

     120     234Chronopost       2024050620240507    20.75    3.10LIVRE

     121     237UPS              2024050520240507    15.27    8.43LIVRE

     122     240Mondial Relay    2025072720250729     1.84   16.87LIVRE

     123     241Chronopost       2024061620240618     5.79   11.49LIVRE

     124     243Chronopost       20251130            16.53   19.45EN_TRANSIT

     125     245UPS              2024022120240226    20.17   18.14LIVRE

     126     247Mondial Relay    20240410             6.16   11.61EN_TRANSIT

     127     250Chronopost       2025070220250707     7.96   18.05LIVRE

     128     251Mondial Relay    2025071520250718     7.10   19.13LIVRE

     129     252Mondial Relay    20241121            10.99    2.25EN_TRANSIT

     130     253Chronopost       2025011020250111     5.68    8.48LIVRE

     131     257DHL              2024060520240608    14.14    9.53LIVRE

     132     259Colissimo        2024052020240522    19.32   18.11LIVRE

     133     261Mondial Relay    2025111920251122     1.49   18.35LIVRE

     134     262Colissimo        20240622            17.89    5.30EN_TRANSIT

     135     263Colissimo        2025120520251213    10.43   17.64LIVRE

     136     266Chronopost       2025110420251106     4.92   10.12RETARD

     137     267Mondial Relay    2024082420240827     8.12   13.09RETARD

     138     268Chronopost       20260102            18.09   19.31EN_TRANSIT

     139     270DHL              20251104            24.42   16.97EN_TRANSIT

     140     273Chronopost       2025022720250302     6.52    8.98LIVRE

     141     276Chronopost       2025041320250414    24.69   19.17LIVRE

     142     277Mondial Relay    20251021            10.76   19.13EN_TRANSIT

     143     279UPS              2025092220250930     2.78    3.19LIVRE

     144     280Chronopost       2024112920241202     0.96    0.29LIVRE

     145     282Chronopost       20250918             1.00   18.86EN_TRANSIT

     146     285Chronopost       20240114            15.78   19.79EN_TRANSIT

     147     286Chronopost       20240908            24.05   16.69EN_TRANSIT

     148     287UPS              2024052920240603    17.14   10.38RETARD

     149     288Chronopost       2025081620250817    17.96   19.53LIVRE

     150     289Chronopost       20251214             4.76    9.39EN_TRANSIT

     151     292Colissimo        2025122620251227    13.85    2.74LIVRE

     152     293UPS              2025092520250927    17.11    3.19LIVRE

     153     294UPS              2025102020251023     8.29    3.12LIVRE

     154     295Colissimo        2025092420250926     0.65    7.23LIVRE

     155     299DHL              2025122720251228    17.28   15.29LIVRE

     156     301Chronopost       2025052820250529    17.31    0.26LIVRE

     157     302Chronopost       2024021020240211     6.17    0.76LIVRE

     158     303DHL              2024120820241209    17.13   17.46LIVRE

     159     304Chronopost       2024112620241128    14.44   19.51LIVRE

     160     305Mondial Relay    2024011720240122     2.97    8.27LIVRE

     161     306UPS              20240627            21.04   15.61EN_TRANSIT

     162     307DHL              2024042120240426     0.43    4.11LIVRE

     163     310DHL              2025092320250925     1.79    0.38LIVRE

     164     311UPS              2025051420250516     0.31   13.65LIVRE

     165     317Mondial Relay    2025040420250406     0.88    6.55LIVRE

     166     320Mondial Relay    2025100220251004    23.65   16.52LIVRE

     167     329Mondial Relay    20241021             3.41    1.91EN_TRANSIT

     168     331Mondial Relay    2025110720251108    24.12    8.12LIVRE

     169     333Chronopost       2025102220251023     3.23   16.65LIVRE

     170     334Chronopost       2024082920240831     3.50   15.78LIVRE

     171     335Mondial Relay    20250404             4.99    9.07EN_TRANSIT

     172     336DHL              2024121220241215    18.56   19.00LIVRE

     173     337DHL              2025061820250620    18.70   13.46LIVRE

     174     339Colissimo        20240301             2.36   18.20EN_TRANSIT

     175     340UPS              2024070920240714    20.90    9.21LIVRE

     176     342Chronopost       20250328             2.24    8.86EN_TRANSIT

     177     343DHL              2025031720250325    20.10   10.62RETARD

     178     344Colissimo        2025052420250527    20.95    8.59LIVRE

     179     345Chronopost       20250506             4.62   19.73EN_TRANSIT

     180     349DHL              2024020720240209    16.59    7.25LIVRE

     181     350DHL              2025070120250702    14.18    8.81LIVRE

     182     352Colissimo        2025092820250930     2.85    3.75LIVRE

     183     354Chronopost       2024120120241216     0.65    6.08LIVRE

     184     355UPS              2025121620251218    21.88    6.47LIVRE

     185     356Mondial Relay    2024061020240611    14.34   17.75LIVRE

     186     359Mondial Relay    20240831            11.73   18.88EN_TRANSIT

     187     361Chronopost       2024062920240704     4.70   15.45LIVRE

     188     364UPS              2024072420240726     1.71   18.22LIVRE

     189     365Colissimo        2024070220240704     3.42   10.10LIVRE

     190     367UPS              20251016             7.16   17.96EN_TRANSIT

     191     368Mondial Relay    20241201            15.19   12.72EN_TRANSIT

     192     369DHL              20250409            17.46   18.61EN_TRANSIT

     193     373Mondial Relay    2024022320240225    22.07   13.46LIVRE

     194     374Mondial Relay    20240522            21.55   10.19EN_TRANSIT

     195     375DHL              20240818            19.44   19.29EN_TRANSIT

     196     376Mondial Relay    2024050820240510     0.41    0.08LIVRE

     197     377Mondial Relay    2024032420240326    24.51   16.91LIVRE

     198     378DHL              2024051720240520    21.76    6.16LIVRE

     199     381UPS              2024061420240619    14.62   16.48RETARD

     200     382DHL              20241221             7.26    4.62EN_TRANSIT

     201     383Colissimo        2025060620250611    17.30    0.62LIVRE

     202     384Mondial Relay    2024021320240215     5.39   12.16LIVRE

     203     385Mondial Relay    20240406            18.57    9.20EN_TRANSIT

     204     386UPS              2025061120250613    12.78    4.44LIVRE

     205     387Mondial Relay    2025011620250118     1.99    9.49LIVRE

     206     389DHL              2024052420240608    16.99    9.73LIVRE

     207     390Colissimo        2024030920240310    20.20   16.72LIVRE

     208     391Chronopost       2025072620250803     8.04    0.51LIVRE

     209     392UPS              2024110520241107    14.68    2.96LIVRE

     210     396DHL              2025121120251214     0.54   17.99LIVRE

     211     397Mondial Relay    20241026             8.63   18.98EN_TRANSIT

     212     400Chronopost       2024081620240819     5.76   15.22RETARD

     213     401UPS              2024052320240531     8.01    3.16LIVRE

     214     402DHL              2025120620251208    20.26    5.67LIVRE

     215     404Colissimo        2025042820250429     4.87   19.27LIVRE

     216     405DHL              2025090920250911    10.71   12.19LIVRE

     217     406DHL              20241226             7.99    6.86EN_TRANSIT

     218     410Colissimo        20240501            22.85    2.96EN_TRANSIT

     219     413Colissimo        2025083020250901     5.03   19.39LIVRE

     220     414Mondial Relay    2024050720240515     7.00    9.36LIVRE

     221     415Mondial Relay    2024070520240706    14.18   18.45LIVRE

     222     420Chronopost       20250204            12.04   14.58EN_TRANSIT

     223     430DHL              20250921             0.94   14.63EN_TRANSIT

     224     435Chronopost       20240523            21.76   18.04EN_TRANSIT

     225     436DHL              2025090720250910     9.78    5.64LIVRE

     226     440DHL              2024110620241108     9.40    6.44RETARD

     227     441UPS              2025102320251026     5.46    6.62RETARD

     228     442Mondial Relay    2025121620251218    15.22   13.38LIVRE

     229     444UPS              2025100620251008    21.47    3.81LIVRE

     230     446Colissimo        2025020620250208     0.92    3.54LIVRE

     231     447Chronopost       2024060220240604    23.71    8.44LIVRE

     232     449Chronopost       2025030420250305     1.74    8.84LIVRE

     233     451UPS              20250905             2.78   15.39EN_TRANSIT

     234     452UPS              2025091220250914     0.79   14.35LIVRE

     235     453Chronopost       20240517             1.16    4.12EN_TRANSIT

     236     454UPS              2024051620240518    11.02    9.46LIVRE

     237     458Colissimo        2025041420250419    13.87    3.85LIVRE

     238     459Chronopost       20250605            14.79   12.64EN_TRANSIT

     239     463UPS              2024012220240125    19.62   12.13LIVRE

     240     466Colissimo        2024040520240406    12.11    3.18LIVRE

     241     467Mondial Relay    2024032920240330     3.32    2.89RETARD

     242     470DHL              2024032720240330     4.71   15.51LIVRE

     243     473UPS              2024051020240512    18.44   10.66LIVRE

     244     474Chronopost       2024071720240722     1.74    3.85LIVRE

     245     475Mondial Relay    20250428            20.80   14.87EN_TRANSIT

     246     476Chronopost       2024120720241215    10.65   11.48LIVRE

     247     479DHL              20241218            10.52    8.34EN_TRANSIT

     248     481DHL              20250522            12.38    0.26EN_TRANSIT

     249     483UPS              2025080120250806    22.18   18.92LIVRE

     250     487DHL              2024033120240401     4.59    9.17LIVRE

     251     488UPS              2025031820250321    12.47   18.03LIVRE

     252     489Mondial Relay    2024112020241121     6.96    6.33RETARD

     253     490UPS              2025081420250816     2.34   18.01LIVRE

     254     491Chronopost       20241221            13.73    3.09EN_TRANSIT

     255     494Chronopost       2024012420240129    22.36   13.67LIVRE

     256     495DHL              2024050620240509     3.16    0.53LIVRE

     257     497UPS              20251121             2.05   10.27EN_TRANSIT

     258     498UPS              2024040720240408    13.66    0.21LIVRE

     259     501UPS              2024050420240505     9.57   19.89LIVRE

     260     502Mondial Relay    2024052820240531    13.19   17.86LIVRE

     261     505Chronopost       2025020120250204    14.00    7.18LIVRE

     262     508UPS              2025052020250523    19.84    1.69LIVRE

     263     509DHL              2025012620250203    13.99   10.39LIVRE

     264     511Colissimo        2025011920250127    17.37   15.51LIVRE

     265     513DHL              2024020220240204     4.43    9.54LIVRE

     266     515Colissimo        20250707            11.89    5.68EN_TRANSIT

     267     516UPS              20241227            24.38   11.52EN_TRANSIT

     268     517Chronopost       2025072620250729    16.27    5.84LIVRE

     269     518Colissimo        2024100620241009     2.47   18.43LIVRE


In [20]:
type(file_contenu)

list

## Fichier Json (JavaScript Object Nottion)

In [21]:
file_json = pd.read_json("data/sessions_web.json")
file_json

,site,periode,nb_sessions,sessions
0,boutique-formation.fr,2025,600,"{'id_session': 'S00001', 'id_client': 290, 'de..."
1,boutique-formation.fr,2025,600,"{'id_session': 'S00002', 'id_client': 277, 'de..."
2,boutique-formation.fr,2025,600,"{'id_session': 'S00003', 'id_client': 273, 'de..."
3,boutique-formation.fr,2025,600,"{'id_session': 'S00004', 'id_client': 148, 'de..."
4,boutique-formation.fr,2025,600,"{'id_session': 'S00005', 'id_client': 48, 'deb..."
...,...,...,...,...
595,boutique-formation.fr,2025,600,"{'id_session': 'S00596', 'id_client': 289, 'de..."
596,boutique-formation.fr,2025,600,"{'id_session': 'S00597', 'id_client': None, 'd..."
597,boutique-formation.fr,2025,600,"{'id_session': 'S00598', 'id_client': 129, 'de..."
598,boutique-formation.fr,2025,600,"{'id_session': 'S00599', 'id_client': 185, 'de..."
599,boutique-formation.fr,2025,600,"{'id_session': 'S00600', 'id_client': None, 'd..."

In [22]:
type(file_json)

pandas.core.frame.DataFrame

## Base de données mysql

In [23]:
%pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in /Users/mac/anaconda3/lib/python3.13/site-packages (2.0.39)
Collecting pymysql
  Using cached pymysql-1.2.3-py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: greenlet!=0.4.17 in /Users/mac/anaconda3/lib/python3.13/site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in /Users/mac/anaconda3/lib/python3.13/site-packages (from sqlalchemy) (4.12.2)
Using cached pymysql-1.2.3-py3-none-any.whl (46 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.3
Note: you may need to restart the kernel to use updated packages.

In [24]:
from sqlalchemy import create_engine

In [25]:
engine = create_engine(
    "mysql+pymysql://root:@127.0.0.1:3306/formation_python_data"
)

In [28]:
df = pd.read_sql("SELECT * FROM clients", engine)
df.head()

,id_client,prenom,nom,sexe,date_naissance,email,ville,segment,date_inscription
0,1,Manon,Fournier,F,1960-01-07,manon.fournier1@exemple.fr,Bordeaux,Particulier,2024-08-10
1,2,Hugo,Petit,F,1983-03-26,hugo.petit2@exemple.fr,Nice,Particulier,2023-09-04
2,3,Nathan,Robert,F,1967-07-12,nathan.robert3@exemple.fr,Lille,Professionnel,2024-03-05
3,4,Sarah,Mercier,M,1990-10-31,sarah.mercier4@exemple.fr,Nice,Particulier,2021-03-25
4,5,Emma,Kone,F,1968-09-17,emma.kone5@exemple.fr,Lyon,Particulier,2024-06-10

In [30]:
import numpy as np
x = np.arange(1,18,2)
y=x.reshape(3,3)
y.min(axis=1)

array([ 1,  7, 13])